[package]
name = "syntomy/knittesting"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Util
TableUtil = "sleitnick/table-util@1.2.0"
loader = "sleitnick/loader@2.0.0"
sift = "csqrl/sift@0.0.11"

# Packages
imgizmo = "jakeywastaken/imgizmo@3.6.0"
janitor = "howmanysmall/janitor@1.18.3"
promise = "evaera/promise@4.0.0"

ProfileService = "surnautica/profileservice@1.0.0"

Knit = "sleitnick/knit@^1.5"
Component = "sleitnick/component@2.4.6"
cmdr = "evaera/cmdr@1.12.0"

shapecasthitbox = "teamswordphin/shapecasthitbox@0.1.7"

camerashake = "developercron/camerashake@0.2.0"
smartbone-2 = "jakeywastaken/smartbone-2@0.5.1"