[package]
name = "syntomy/knittesting"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.5"
ProfileService = "surnautica/profileservice@1.0.0"
Trove = "sleitnick/trove@1.0.0"
Component = "sleitnick/component@2.4.6"
Loader = "sleitnick/loader@2.0.0"
TableUtil = "sleitnick/table-util@1.2.0"